name: lbinfra

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          version: latest

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Terraform Init & Plan for Present_module/dev
      - name: Terraform Init (Present_module/dev)
        run: terraform init
        working-directory: Present_module/dev

      - name: Terraform Plan (Present_module/dev)
        run: terraform plan
        working-directory: Present_module/dev

      # Terraform Init & Plan for child_module
      - name: Terraform Init (child_module)
        run: terraform init
        working-directory: child_module

      - name: Terraform Plan (child_module)
        run: terraform plan
        working-directory: child_module
